# Generated by Django 5.0.6 on 2024-06-09 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='taskAssigned',
            field=models.DateField(default=datetime.date(2024, 6, 9)),
            preserve_default=False,
        ),
    ]
